services:
  back:
    container_name: dash-back
    build: docker/node
    volumes:
      - "./back:/www"
    ports:
      - "3000:3000"
    entrypoint:
      /bin/sh -c "npm i && npm run start:dev"

  front:
    container_name: dash-front
    build: docker/node
    volumes:
      - "./front:/www"
    ports:
      - "4200:4200"
    entrypoint:
      /bin/sh -c "npm i && ng s"

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=db_name"
      - "MONGO_INITDB_ROOT_USERNAME=db_user"
      - "MONGO_INITDB_ROOT_PASSWORD=db_pass"
